export const styles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "1.5rem",
    fontFamily: "system-ui, sans-serif",
    background: "#f7f7f7",
  },
  box: {
    background: "#fff",
    border: "1px solid #e0e0e0",
    borderRadius: 12,
    padding: "2rem",
    maxWidth: 480,
    width: "100%",
  },
  label: { fontSize: 12, color: "#999", marginBottom: 4 },
  title: { fontSize: 22, fontWeight: 600, color: "#111", margin: "0 0 1rem" },
  img: {
    width: "100%",
    height: 200,
    objectFit: "cover",
    borderRadius: 8,
    marginBottom: "1rem",
  },
  text: { fontSize: 15, color: "#555", lineHeight: 1.7, margin: "0 0 1rem" },
  hr: { border: "none", borderTop: "1px solid #eee", margin: "1.25rem 0" },
  question: { fontSize: 16, fontWeight: 500, color: "#111", marginBottom: "1rem" },
  row: { display: "flex", gap: 8 },
  input: {
    flex: 1,
    fontSize: 15,
    padding: "0.6rem 0.75rem",
    border: "1px solid #ccc",
    borderRadius: 8,
    outline: "none",
    color: "#111",
  },
  btn: {
    padding: "0.6rem 1.25rem",
    background: "#111",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    fontSize: 15,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  wrong: { marginTop: "0.75rem", fontSize: 14, color: "#c0392b" },
  right: { marginTop: "0.75rem", fontSize: 14, color: "#27ae60", fontWeight: 500 },
  hint: { marginTop: "1rem", fontSize: 13, color: "#888", lineHeight: 1.6 },
};
